---
- name: SERVICES_ALL
  hosts: WFM_FHC_MDF_CORE1
  collections:
    - arubanetworks.aoscx
  vars:
    - ansible_connection: network_cli
  tasks:
    - name:
      aoscx_config:
        lines:
          - spanning-tree
          - spanning-tree mode rpvst
          - spanning-tree bpdu-guard timeout 300
          - snmp-server community W@c0_Wr1t3
          - snmp-server community W@c0_R3@d
          - snmp-server system-contact Support@wacofhc.org
          - ntp server 10.132.1.15
          - ntp enable
          - clock timezone us/central
          - ip dns domain-name wacofhc.org
          - ip dns server-address 10.132.1.20
          - ip dns server-address 10.132.1.21

- name: SERVICES_MDF
  hosts: WFM_FHC_MDF_CORE1
  collections:
      - arubanetworks.aoscx
  vars:
    - ansible_connection: network_cli
  tasks:
    - name: SETTING PRIORITY 1 TO MDF SWITCHES
      aoscx_config:
        lines:
          - spanning-tree priority 1

- name: BPDU_GUARD
  hosts: WFM_FHC_MDF_CORE1
  collections:
    - arubanetworks.aoscx
  vars:
    - ansible_connection: network_cli
  tasks:
    - name: BPDU_GUARD & LOOP_PROTECT TO ACCESS PORTS
      aoscx_config:
        lines:
          - spanning-tree bpdu-guard
          - loop-protect
        parents:
          - interface 1/1/1-1/1/48
          - interface 2/1/1-2/1/48
          - interface 3/1/1-3/1/48
          - interface 4/1/1-4/1/48
        match: none
